const wordPairs = [
  { civilian: "Airport", imposter: "Suitcase" },
  { civilian: "Airplane", imposter: "Passport" },
  { civilian: "Aquarium", imposter: "Glass" },
  { civilian: "Arcade", imposter: "Token" },
  { civilian: "Astronaut", imposter: "Helmet" },
  { civilian: "Bakery", imposter: "Oven" },
  { civilian: "Bank", imposter: "Wallet" },
  { civilian: "Barbecue", imposter: "Grill" },
  { civilian: "Baseball", imposter: "Glove" },
  { civilian: "Beach", imposter: "Sunscreen" },
  { civilian: "Birthday", imposter: "Candle" },
  { civilian: "Breakfast", imposter: "Toaster" },
  { civilian: "Camping", imposter: "Tent" },
  { civilian: "Carnival", imposter: "Balloon" },
  { civilian: "Castle", imposter: "Crown" },
  { civilian: "Cat", imposter: "Yarn" },
  { civilian: "Chef", imposter: "Apron" },
  { civilian: "Chess", imposter: "Timer" },
  { civilian: "Cinema", imposter: "Popcorn" },
  { civilian: "Circus", imposter: "Clown" },
  { civilian: "Classroom", imposter: "Chalk" },
  { civilian: "Concert", imposter: "Ticket" },
  { civilian: "Construction", imposter: "Blueprint" },
  { civilian: "Dentist", imposter: "Toothbrush" },
  { civilian: "Desert", imposter: "Cactus" },
  { civilian: "Detective", imposter: "Magnifying Glass" },
  { civilian: "Dog", imposter: "Leash" },
  { civilian: "Farm", imposter: "Tractor" },
  { civilian: "Firefighter", imposter: "Ladder" },
  { civilian: "Fishing", imposter: "Bait" },
  { civilian: "Garden", imposter: "Hose" },
  { civilian: "Gym", imposter: "Towel" },
  { civilian: "Haircut", imposter: "Scissors" },
  { civilian: "Halloween", imposter: "Pumpkin" },
  { civilian: "Hospital", imposter: "Ambulance" },
  { civilian: "Hotel", imposter: "Keycard" },
  { civilian: "Kitchen", imposter: "Recipe" },
  { civilian: "Library", imposter: "Bookmark" },
  { civilian: "Mail", imposter: "Envelope" },
  { civilian: "Marathon", imposter: "Medal" },
  { civilian: "Museum", imposter: "Painting" },
  { civilian: "Ocean", imposter: "Lighthouse" },
  { civilian: "Office", imposter: "Calendar" },
  { civilian: "Painter", imposter: "Canvas" },
  { civilian: "Park", imposter: "Bench" },
  { civilian: "Phone", imposter: "Charger" },
  { civilian: "Picnic", imposter: "Basket" },
  { civilian: "Pirate", imposter: "Treasure" },
  { civilian: "Pizza", imposter: "Delivery" },
  { civilian: "Playground", imposter: "Swing" },
  { civilian: "Police", imposter: "Badge" },
  { civilian: "Pool", imposter: "Lifeguard" },
  { civilian: "Rain", imposter: "Umbrella" },
  { civilian: "Restaurant", imposter: "Menu" },
  { civilian: "Road Trip", imposter: "Map" },
  { civilian: "Robot", imposter: "Battery" },
  { civilian: "School", imposter: "Backpack" },
  { civilian: "Scientist", imposter: "Microscope" },
  { civilian: "Ship", imposter: "Anchor" },
  { civilian: "Skateboard", imposter: "Ramp" },
  { civilian: "Skiing", imposter: "Lift" },
  { civilian: "Snow", imposter: "Sled" },
  { civilian: "Space", imposter: "Rocket" },
  { civilian: "Supermarket", imposter: "Cart" },
  { civilian: "Teacher", imposter: "Homework" },
  { civilian: "Television", imposter: "Remote" },
  { civilian: "Theater", imposter: "Costume" },
  { civilian: "Train", imposter: "Platform" },
  { civilian: "Vacation", imposter: "Postcard" },
  { civilian: "Video Game", imposter: "Controller" },
  { civilian: "Wedding", imposter: "Flowers" },
  { civilian: "Writer", imposter: "Notebook" },
  { civilian: "Zoo", imposter: "Binoculars" },
  { civilian: "Baby", imposter: "Stroller" },
  { civilian: "Boat", imposter: "Life Jacket" },
  { civilian: "Campfire", imposter: "Marshmallow" },
  { civilian: "Computer", imposter: "Keyboard" },
  { civilian: "Doctor", imposter: "Stethoscope" },
  { civilian: "Dinosaur", imposter: "Fossil" },
  { civilian: "Elevator", imposter: "Button" },
  { civilian: "Festival", imposter: "Wristband" },
  { civilian: "Football", imposter: "Whistle" },
  { civilian: "Forest", imposter: "Cabin" },
  { civilian: "Graduation", imposter: "Diploma" },
  { civilian: "Hiking", imposter: "Trail" },
  { civilian: "Ice Cream", imposter: "Cone" },
  { civilian: "Laundry", imposter: "Detergent" },
  { civilian: "Magic", imposter: "Wand" },
  { civilian: "Morning", imposter: "Alarm" },
  { civilian: "Mountain", imposter: "Climbing Rope" },
  { civilian: "Night", imposter: "Lantern" },
  { civilian: "Photography", imposter: "Camera" },
  { civilian: "Dinner", imposter: "Reservation" },
  { civilian: "Soccer", imposter: "Goal" },
  { civilian: "Summer", imposter: "Sunglasses" },
  { civilian: "Swimming", imposter: "Float" },
  { civilian: "Taxi", imposter: "Meter" },
  { civilian: "Jungle", imposter: "Compass" },
  { civilian: "Winter", imposter: "Coat" },
  { civilian: "Workshop", imposter: "Toolbox" },
  { civilian: "Anniversary", imposter: "Bouquet" },
  { civilian: "Archaeology", imposter: "Artifact" },
  { civilian: "Auction", imposter: "Gavel" },
  { civilian: "Ballet", imposter: "Tutu" },
  { civilian: "Blizzard", imposter: "Snowplow" },
  { civilian: "Board Game", imposter: "Dice" },
  { civilian: "Bookstore", imposter: "Shelf" },
  { civilian: "Bowling", imposter: "Pins" },
  { civilian: "Bridge", imposter: "River" },
  { civilian: "Cafeteria", imposter: "Tray" },
  { civilian: "Schedule", imposter: "Reminder" },
  { civilian: "Car Wash", imposter: "Soap" },
  { civilian: "Carpenter", imposter: "Hammer" },
  { civilian: "Cave", imposter: "Flashlight" },
  { civilian: "Chemistry", imposter: "Beaker" },
  { civilian: "Choir", imposter: "Microphone" },
  { civilian: "Coffee Shop", imposter: "Mug" },
  { civilian: "Courtroom", imposter: "Witness" },
  { civilian: "Cruise", imposter: "Deck" },
  { civilian: "Diary", imposter: "Lock" },
  { civilian: "Dragon", imposter: "Treasure Chest" },
  { civilian: "Emergency", imposter: "Siren" },
  { civilian: "Escape Room", imposter: "Puzzle" },
  { civilian: "Factory", imposter: "Machine" },
  { civilian: "Fashion", imposter: "Runway" },
  { civilian: "Ferry", imposter: "Dock" },
  { civilian: "Fireplace", imposter: "Chimney" },
  { civilian: "Garage", imposter: "Wrench" },
  { civilian: "Geography", imposter: "Atlas" },
  { civilian: "Greenhouse", imposter: "Seedling" },
  { civilian: "Grocery", imposter: "Receipt" },
  { civilian: "Harbor", imposter: "Buoy" },
  { civilian: "Harvest", imposter: "Scarecrow" },
  { civilian: "Haunted House", imposter: "Ghost" },
  { civilian: "Highway", imposter: "Tollbooth" },
  { civilian: "Hurricane", imposter: "Sandbag" },
  { civilian: "Island", imposter: "Palm Tree" },
  { civilian: "Journalist", imposter: "Headline" },
  { civilian: "Karaoke", imposter: "Lyrics" },
  { civilian: "Laboratory", imposter: "Test Tube" },
  { civilian: "Lemonade Stand", imposter: "Pitcher" },
  { civilian: "Lighthouse Keeper", imposter: "Beacon" },
  { civilian: "Locker Room", imposter: "Jersey" },
  { civilian: "Mall", imposter: "Escalator" },
  { civilian: "Mechanic", imposter: "Oil" },
  { civilian: "Meteor Shower", imposter: "Telescope" },
  { civilian: "Monopoly", imposter: "Rent" },
  { civilian: "Newsroom", imposter: "Deadline" },
  { civilian: "Orchestra", imposter: "Conductor" },
  { civilian: "Parade", imposter: "Confetti" },
  { civilian: "Pharmacy", imposter: "Prescription" },
  { civilian: "Pottery", imposter: "Clay" },
  { civilian: "Ranch", imposter: "Saddle" },
  { civilian: "Recycling", imposter: "Bin" },
  { civilian: "Rehearsal", imposter: "Script" },
  { civilian: "Safari", imposter: "Jeep" },
  { civilian: "Sandcastle", imposter: "Bucket" },
  { civilian: "Science Fair", imposter: "Poster" },
  { civilian: "Seashell", imposter: "Shore" },
  { civilian: "Security", imposter: "Camera Lens" },
  { civilian: "Sleepover", imposter: "Pillow" },
  { civilian: "Stadium", imposter: "Scoreboard" },
  { civilian: "Studio", imposter: "Spotlight" },
  { civilian: "Surfing", imposter: "Wave" },
  { civilian: "Tailor", imposter: "Measuring Tape" },
  { civilian: "Tea Party", imposter: "Saucer" },
  { civilian: "Temple", imposter: "Statue" },
  { civilian: "Traffic", imposter: "Signal" },
  { civilian: "University", imposter: "Lecture" },
  { civilian: "Volcano", imposter: "Lava" },
  { civilian: "Warehouse", imposter: "Forklift" },
  { civilian: "Waterfall", imposter: "Mist" },
  { civilian: "Weather", imposter: "Forecast" },
  { civilian: "Windmill", imposter: "Breeze" },
  { civilian: "Yoga", imposter: "Mat" },
  { civilian: "Abandoned House", imposter: "Dust" },
  { civilian: "Adventure", imposter: "Quest" },
  { civilian: "Apology", imposter: "Forgiveness" },
  { civilian: "Architecture", imposter: "Sketch" },
  { civilian: "Astronomy", imposter: "Constellation" },
  { civilian: "Biography", imposter: "Childhood" },
  { civilian: "Budget", imposter: "Expense" },
  { civilian: "Campaign", imposter: "Slogan" },
  { civilian: "Celebration", imposter: "Toast" },
  { civilian: "Ceremony", imposter: "Invitation" },
  { civilian: "Competition", imposter: "Trophy" },
  { civilian: "Conversation", imposter: "Awkward Silence" },
  { civilian: "Debate", imposter: "Argument" },
  { civilian: "Discovery", imposter: "Clue" },
  { civilian: "Drama", imposter: "Backstage" },
  { civilian: "Election", imposter: "Ballot" },
  { civilian: "Experiment", imposter: "Hypothesis" },
  { civilian: "Fame", imposter: "Autograph" },
  { civilian: "Friendship", imposter: "Secret" },
  { civilian: "History", imposter: "Timeline" },
  { civilian: "Imagination", imposter: "Dream" },
  { civilian: "Interview", imposter: "Resume" },
  { civilian: "Investigation", imposter: "Fingerprint" },
  { civilian: "Justice", imposter: "Verdict" },
  { civilian: "Leadership", imposter: "Responsibility" },
  { civilian: "Legend", imposter: "Myth" },
  { civilian: "Memory", imposter: "Photograph" },
  { civilian: "Mystery", imposter: "Footprint" },
  { civilian: "Negotiation", imposter: "Compromise" },
  { civilian: "Observation", imposter: "Detail" },
  { civilian: "Opportunity", imposter: "Risk" },
  { civilian: "Performance", imposter: "Applause" },
  { civilian: "Prediction", imposter: "Guess" },
  { civilian: "Promise", imposter: "Trust" },
  { civilian: "Reputation", imposter: "Rumor" },
  { civilian: "Strategy", imposter: "Plan" },
  { civilian: "Tradition", imposter: "Ritual" },
  { civilian: "Victory", imposter: "Prize" },
  { civilian: "Wisdom", imposter: "Advice" },
  { civilian: "Workshop Class", imposter: "Instruction" },
  { civilian: "Treasure Hunt", imposter: "Riddle" }
];

function isSamePair(a, b) {
  return a && b && a.civilian === b.civilian && a.imposter === b.imposter;
}

function getRandomPair(excludePair = null) {
  const availablePairs = wordPairs.filter(pair => !isSamePair(pair, excludePair));
  const pairs = availablePairs.length > 0 ? availablePairs : wordPairs;
  return pairs[Math.floor(Math.random() * pairs.length)];
}

module.exports = { wordPairs, getRandomPair };
